# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Game' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Game


  target 'GameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Game-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Game-tvOS

  target 'Game-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
